name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Show .NET Version
      run: dotnet --version

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Execute Unit Tests
      run: dotnet test

    - name: Publish Project
      run: |
        echo "Publishing the project..."
        dotnet publish --configuration Release --output .\publish

    # Add steps for IIS management (similar to your Bitbucket pipeline)
    - name: Stop IIS Process or Application Pool
      run: |
        echo "Stopping IIS process or application pool..."
        PowerShell -Command "Import-Module WebAdministration"
        PowerShell -Command "Stop-WebAppPool -Name 'ErgotronChatbot'"
        PowerShell -Command "Stop-WebSite -Name 'ErgotronChatbot'"
        Start-Sleep -Seconds 10  # Wait for IIS to stop completely

    - name: Copy Published Files to Target Directory
      run: |
        echo "Copying published files to the target directory..."
        $destinationPath = 'C:\Sites\ErgotronChatbot'
        if (-Not (Test-Path $destinationPath)) { New-Item -ItemType Directory -Force -Path $destinationPath }
        Copy-Item -Path .\publish\* -Destination $destinationPath -Recurse -Force

    - name: Start IIS Process or Application Pool
      run: |
        echo "Starting IIS process or application pool..."
        PowerShell -Command "Start-WebAppPool -Name 'ErgotronChatbot'"
        PowerShell -Command "Start-WebSite -Name 'ErgotronChatbot'"
