name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Show .NET Version
      run: dotnet --version

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Execute Unit Tests
      run: dotnet test

    - name: Publish Project
      run: |
        echo "Publishing the project..."
        dotnet publish --configuration Release --output .\publish
        
    - name: Stop IIS app pool or website
      run: |
        Start-Process powershell -ArgumentList "Import-Module WebAdministration; Stop-WebAppPool -Name 'ErgotronChatbot'; Stop-WebSite -Name 'ErgotronChatbot'; Start-Sleep -Seconds 10" -Verb runAs

    # Stop IIS app pool or website using Windows PowerShell
    # - name: Stop IIS app pool or website
    #   run: |
    #     Import-Module WebAdministration 
    #     Stop-WebAppPool -Name "ErgotronChatbot"
    #     Stop-WebSite -Name "ErgotronChatbot"
    #     Start-Sleep -Seconds 10  # Wait for 10 seconds to ensure IIS stops completely
        

    # - name: Copy published files
    #   run: |
    #     $destinationPath = 'C:\Sites\ErgotronChatbot'
    #     Copy-Item -Path .\publish\* -Destination $destinationPath -Recurse -Force

    # # Start IIS app pool or website using Windows PowerShell
    # - name: Start IIS app pool or website
    #   run: |
    #     Start-WebAppPool -Name "ErgotronChatbot"
    #     Start-WebSite -Name "ErgotronChatbot"
        
