name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Show .NET Version
      run: dotnet --version

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Execute Unit Tests
      run: dotnet test

    - name: Publish Project
      run: |
        echo "Publishing the project..."
        dotnet publish --configuration Release --output .\publish

    # Install IIS and WebAdministration module
    - name: Install IIS and WebAdministration Module
      run: |
        Install-WindowsFeature -Name Web-Server, Web-WebServer, Web-App-Dev, Web-Asp-Net45, Web-Management-Tools
        Import-Module WebAdministration

    - name: Stop IIS Process or Application Pool
      run: |
        echo "Stopping IIS process or application pool..."
        PowerShell -Command "Stop-WebAppPool -Name 'ErgotronChatbot' -ErrorAction SilentlyContinue"
        PowerShell -Command "Stop-WebSite -Name 'ErgotronChatbot' -ErrorAction SilentlyContinue"
        Start-Sleep -Seconds 10  # Wait for IIS to stop completely

    - name: Copy Published Files to Target Directory
      run: |
        echo "Copying published files to the target directory..."
        Copy-Item -Path .\publish\* -Destination C:\Sites\ErgotronChatbot -Recurse -Force

    - name: Start IIS Process or Application Pool
      run: |
        echo "Starting IIS process or application pool..."
        PowerShell -Command "Start-WebAppPool -Name 'ErgotronChatbot'"
        PowerShell -Command "Start-WebSite -Name 'ErgotronChatbot'"

    # Upload the publish folder as an artifact
    - name: Upload Published Files
      uses: actions/upload-artifact@v3
      with:
        name: published-files
        path: ./publish
